// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2026. 10. 5. 오전 9:07:01
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/이상민/orca/leePF/running/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/이상민/orca/leePF/running/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/이상민/orca/leePF/running/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/이상민/orca/leePF/running/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/이상민/orca/leePF/running/plugins/**/*.{js,ts,mjs}","C:/Users/이상민/orca/leePF/running/composables/**/*.{js,ts,mjs}","C:/Users/이상민/orca/leePF/running/utils/**/*.{js,ts,mjs}","C:/Users/이상민/orca/leePF/running/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/이상민/orca/leePF/running/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/이상민/orca/leePF/running/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/이상민/orca/leePF/running/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;