// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/baby/benefits': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/baby/benefits.get').default>>>>
    }
    '/api/baby/checklists': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/baby/checklists.get').default>>>>
    }
    '/api/baby/childcare/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/baby/childcare/[id].get').default>>>>
    }
    '/api/baby/childcare': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/baby/childcare/index.get').default>>>>
    }
    '/api/baby/hospitals': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/baby/hospitals.get').default>>>>
    }
    '/api/health': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/health.get').default>>>>
    }
    '/api/location/search': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/location/search.get').default>>>>
    }
    '/api/running/marathons/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/running/marathons/[id].get').default>>>>
    }
    '/api/running/marathons': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/running/marathons/index.get').default>>>>
    }
    '/api/running/outfit': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/running/outfit.post').default>>>>
    }
    '/api/running/pace': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/running/pace.post').default>>>>
    }
    '/api/running/weather': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/running/weather.get').default>>>>
    }
    '/robots.txt': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/robots.txt').default>>>>
    }
    '/sitemap.xml': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/sitemap.xml').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}